
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sajid
 */
public class JobMatch extends javax.swing.JFrame {

    final String PROJECT_ROOT = System.getProperty("user.dir");
    
    /**
     * Creates new form JobMatch
     */
    public JobMatch() {
        initComponents();
        BackgroundBack.setVisible(false);
        
        JobMatchScript();
        DisplayJobs();
        
        Jobs.setOpaque(false);
        Jobs.setBackground(new Color(0, 0, 0, 0));
        
        Scroll.getViewport().setOpaque(false);
        Scroll.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Scroll = new javax.swing.JScrollPane();
        Jobs = new javax.swing.JTextArea();
        BackgroundBack = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setContentAreaFilled(false);
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 60, 60, 70));

        Scroll.setBorder(null);
        Scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Jobs.setEditable(false);
        Jobs.setColumns(20);
        Jobs.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Jobs.setForeground(new java.awt.Color(255, 255, 255));
        Jobs.setRows(5);
        Scroll.setViewportView(Jobs);

        getContentPane().add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 1450, 620));

        BackgroundBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/job_back.png"))); // NOI18N
        getContentPane().add(BackgroundBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/job_main.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.dispose();
        LandingPage.landing.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        BackgroundBack.setVisible(true);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        BackgroundBack.setVisible(false);
    }//GEN-LAST:event_BackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobMatch().setVisible(true);
            }
        });
    }
    
    void JobMatchScript() {
        try {
            String path = String.format("%s/data/Matcher.py", PROJECT_ROOT);
            Process p = new ProcessBuilder("C:\\Users\\sajid\\Anaconda3\\python.exe", path, "file.docx").start();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    void DisplayJobs() {
        String path = String.format("%s/data/Output.csv", PROJECT_ROOT);
        String line = "";
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(path));
            int i = 0;
            String format ="%-20s%-100s%-20s%-13s%n";
            String linedisplay; 
            while ((line = br.readLine()) != null) {
                if (i==0) {
                    i++;
                }
                else{
                String[] values = line.split(",");
                linedisplay = String.format(format, i, values[1], values[3], values[2]);
                Jobs.append(linedisplay);
                i++;
                } 
            }
        }
        catch (FileNotFoundException e){
            e.printStackTrace();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BackgroundBack;
    private javax.swing.JTextArea Jobs;
    private javax.swing.JScrollPane Scroll;
    // End of variables declaration//GEN-END:variables
}
