
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.text.StyledDocument;
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sajid
 */
public class KeywordAnalysis extends javax.swing.JFrame {

    /**
     * Creates new form KeywordAnalysis
     */
    public KeywordAnalysis() {
        initComponents();
        BackgroundConfirm.setVisible(false);
        BackgroundBack.setVisible(false);
        BackgroundHelp.setVisible(false);
        BackgroundDropdown.setVisible(false);
        
        

        Results.setBorder(null);
        Results.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dropdown = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        PerformAnalysis = new javax.swing.JButton();
        Results = new javax.swing.JTextArea();
        BackgroundDropdown = new javax.swing.JLabel();
        BackgroundHelp = new javax.swing.JLabel();
        BackgroundBack = new javax.swing.JLabel();
        BackgroundConfirm = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dropdown.setContentAreaFilled(false);
        Dropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DropdownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DropdownMouseExited(evt);
            }
        });
        Dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropdownActionPerformed(evt);
            }
        });
        getContentPane().add(Dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 200, -1, 40));

        Back.setContentAreaFilled(false);
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 70, 70));

        Help.setContentAreaFilled(false);
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HelpMouseExited(evt);
            }
        });
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        getContentPane().add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 90, 90));

        PerformAnalysis.setContentAreaFilled(false);
        PerformAnalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PerformAnalysisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PerformAnalysisMouseExited(evt);
            }
        });
        PerformAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerformAnalysisActionPerformed(evt);
            }
        });
        getContentPane().add(PerformAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 330, 60));

        Results.setEditable(false);
        Results.setColumns(20);
        Results.setFont(new java.awt.Font("Segoe UI Black", 0, 32)); // NOI18N
        Results.setForeground(new java.awt.Color(255, 255, 255));
        Results.setRows(5);
        Results.setOpaque(false);
        getContentPane().add(Results, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 1460, 460));

        BackgroundDropdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key_dropdown.png"))); // NOI18N
        getContentPane().add(BackgroundDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgroundHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key_help.png"))); // NOI18N
        getContentPane().add(BackgroundHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgroundBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key_back.png"))); // NOI18N
        getContentPane().add(BackgroundBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgroundConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key_confirm.png"))); // NOI18N
        getContentPane().add(BackgroundConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key_main.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerformAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerformAnalysisActionPerformed
        KeywordAnalysisScript();
    }//GEN-LAST:event_PerformAnalysisActionPerformed

    private void PerformAnalysisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerformAnalysisMouseEntered
        BackgroundConfirm.setVisible(true);
    }//GEN-LAST:event_PerformAnalysisMouseEntered

    private void PerformAnalysisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerformAnalysisMouseExited
        BackgroundConfirm.setVisible(false);
    }//GEN-LAST:event_PerformAnalysisMouseExited

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        BackgroundBack.setVisible(true);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
       BackgroundBack.setVisible(false);
    }//GEN-LAST:event_BackMouseExited

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.dispose();
        LandingPage.landing.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void HelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseEntered
        BackgroundHelp.setVisible(true);
    }//GEN-LAST:event_HelpMouseEntered

    private void HelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseExited
        BackgroundHelp.setVisible(false);
    }//GEN-LAST:event_HelpMouseExited

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    private void DropdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DropdownMouseEntered
        BackgroundDropdown.setVisible(true);
    }//GEN-LAST:event_DropdownMouseEntered

    private void DropdownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DropdownMouseExited
        BackgroundDropdown.setVisible(false);
    }//GEN-LAST:event_DropdownMouseExited

    private void DropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeywordAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeywordAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeywordAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeywordAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeywordAnalysis().setVisible(true);
            }
        });
    }

    
   void KeywordAnalysisScript(){
       final String PROJECT_ROOT = System.getProperty("user.dir");
        try {
            String s = null;

            String path = String.format("%s/data/KeyWord.py", PROJECT_ROOT);
            Process p = new ProcessBuilder("C:\\Users\\sajid\\Anaconda3\\python.exe", path, "file.docx").start();

            BufferedReader stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()));

            BufferedReader stdError = new BufferedReader(new InputStreamReader(p.getErrorStream()));

            // read the output from the command
            System.out.println("Here is the standard output of the command:\n");
            while ((s = stdInput.readLine()) != null) {
                Results.append(s + "\n");
            }
            while ((s = stdError.readLine()) != null) {
                Results.append(s+ "\n");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BackgroundBack;
    private javax.swing.JLabel BackgroundConfirm;
    private javax.swing.JLabel BackgroundDropdown;
    private javax.swing.JLabel BackgroundHelp;
    private javax.swing.JButton Dropdown;
    private javax.swing.JButton Help;
    private javax.swing.JButton PerformAnalysis;
    private javax.swing.JTextArea Results;
    // End of variables declaration//GEN-END:variables
}
