


import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sajid
 */
public class LandingPage extends javax.swing.JFrame {
    
    public static File ResumeDoc;
    public static LandingPage landing = new LandingPage();
   
    
    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
        BackgroundKeywordAnalysis.setVisible(false);
        BackgroundResumeBuilder.setVisible(false);
        BackgroundJobMatch.setVisible(false);
        BackgroundAddResume.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Resume = new javax.swing.JLabel();
        AddResume = new javax.swing.JButton();
        JobMatch = new javax.swing.JButton();
        ResumeBuilder = new javax.swing.JButton();
        KeywordAnalysis = new javax.swing.JButton();
        BackgroundAddResume = new javax.swing.JLabel();
        BackgroundJobMatch = new javax.swing.JLabel();
        BackgroundResumeBuilder = new javax.swing.JLabel();
        BackgroundKeywordAnalysis = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Resume.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Resume.setForeground(new java.awt.Color(255, 255, 255));
        Resume.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Resume.setText("ADD YOUR RESUME");
        getContentPane().add(Resume, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 570, 100));

        AddResume.setBorderPainted(false);
        AddResume.setContentAreaFilled(false);
        AddResume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddResumeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddResumeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddResumeMousePressed(evt);
            }
        });
        AddResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddResumeActionPerformed(evt);
            }
        });
        getContentPane().add(AddResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(873, 80, 40, 30));

        JobMatch.setBorderPainted(false);
        JobMatch.setContentAreaFilled(false);
        JobMatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobMatchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobMatchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JobMatchMousePressed(evt);
            }
        });
        JobMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobMatchActionPerformed(evt);
            }
        });
        getContentPane().add(JobMatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 330, 330, 500));

        ResumeBuilder.setBorderPainted(false);
        ResumeBuilder.setContentAreaFilled(false);
        ResumeBuilder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResumeBuilderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResumeBuilderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ResumeBuilderMousePressed(evt);
            }
        });
        ResumeBuilder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeBuilderActionPerformed(evt);
            }
        });
        getContentPane().add(ResumeBuilder, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 320, 500));

        KeywordAnalysis.setBorderPainted(false);
        KeywordAnalysis.setContentAreaFilled(false);
        KeywordAnalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KeywordAnalysisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KeywordAnalysisMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KeywordAnalysisMousePressed(evt);
            }
        });
        KeywordAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeywordAnalysisActionPerformed(evt);
            }
        });
        getContentPane().add(KeywordAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 330, 500));

        BackgroundAddResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_resume.png"))); // NOI18N
        getContentPane().add(BackgroundAddResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgroundJobMatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/job_match.png"))); // NOI18N
        getContentPane().add(BackgroundJobMatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgroundResumeBuilder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resume_builder.png"))); // NOI18N
        getContentPane().add(BackgroundResumeBuilder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgroundKeywordAnalysis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keyword_analysis.png"))); // NOI18N
        getContentPane().add(BackgroundKeywordAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main_page.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeywordAnalysisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeywordAnalysisMouseEntered
        BackgroundKeywordAnalysis.setVisible(true);
    }//GEN-LAST:event_KeywordAnalysisMouseEntered

    private void KeywordAnalysisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeywordAnalysisMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeywordAnalysisMousePressed

    private void KeywordAnalysisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeywordAnalysisMouseExited
        BackgroundKeywordAnalysis.setVisible(false);
    }//GEN-LAST:event_KeywordAnalysisMouseExited

    private void ResumeBuilderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumeBuilderMouseEntered
        BackgroundResumeBuilder.setVisible(true);
    }//GEN-LAST:event_ResumeBuilderMouseEntered

    private void ResumeBuilderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumeBuilderMouseExited
        BackgroundResumeBuilder.setVisible(false);
    }//GEN-LAST:event_ResumeBuilderMouseExited

    private void ResumeBuilderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumeBuilderMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResumeBuilderMousePressed

    private void JobMatchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobMatchMouseEntered
        BackgroundJobMatch.setVisible(true);
    }//GEN-LAST:event_JobMatchMouseEntered

    private void JobMatchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobMatchMouseExited
        BackgroundJobMatch.setVisible(false);
    }//GEN-LAST:event_JobMatchMouseExited

    private void JobMatchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobMatchMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JobMatchMousePressed

    private void AddResumeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddResumeMouseEntered
        BackgroundAddResume.setVisible(true);
    }//GEN-LAST:event_AddResumeMouseEntered

    private void AddResumeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddResumeMouseExited
        BackgroundAddResume.setVisible(false);
    }//GEN-LAST:event_AddResumeMouseExited

    private void AddResumeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddResumeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddResumeMousePressed

    private void AddResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddResumeActionPerformed
        try {
            StoreResume();
            Resume.setText(ResumeDoc.getName());
        } catch (IOException ex) {
            Logger.getLogger(LandingPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddResumeActionPerformed

    private void KeywordAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeywordAnalysisActionPerformed
        if (ResumeDoc != null) {
           landing.setVisible(false);
           KeywordAnalysis keyword = new KeywordAnalysis();
           keyword.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, ".DOCX RESUME FILE NOT UPLOADED", "ERROR", 1);
        }
    }//GEN-LAST:event_KeywordAnalysisActionPerformed

    private void JobMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobMatchActionPerformed
      if (ResumeDoc != null) {
        landing.setVisible(false);
        JobMatch job = new JobMatch();
        job.setVisible(true);}
      else {
            JOptionPane.showMessageDialog(null, ".DOCX RESUME FILE NOT UPLOADED", "ERROR", 1);
        }
    }//GEN-LAST:event_JobMatchActionPerformed

    private void ResumeBuilderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeBuilderActionPerformed
           landing.setVisible(false);
           ResumeBuilder resume = new ResumeBuilder();
           resume.setVisible(true);
    }//GEN-LAST:event_ResumeBuilderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                landing.setVisible(true);
            }
        });
    }
    
    void copyFile(File source, File destination) throws IOException {
        byte[] buffer = new byte[1024];
        FileInputStream fis = new FileInputStream(source);
        FileOutputStream fos = new FileOutputStream(destination);

        int read;
        while ((read = fis.read(buffer)) != -1) {
            fos.write(buffer, 0, read);
        }
        fos.close();
        fis.close();
    }

    void StoreResume() throws IOException {
        File destination = new File(String.format("%s/scripts/file.docx", System.getProperty("user.dir")));
        destination.delete();

        Scanner fileIN;
        int response;
        JFileChooser chooser = new JFileChooser(".");

        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        response = chooser.showOpenDialog(null);

        if (response == JFileChooser.APPROVE_OPTION) {
            File source = chooser.getSelectedFile();
            ResumeDoc = source;
            System.out.println(ResumeDoc.getName());
            try {
                copyFile(source, destination);
            } catch (IOException e) {
                System.out.println(e);
            }

        }
    }

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddResume;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BackgroundAddResume;
    private javax.swing.JLabel BackgroundJobMatch;
    private javax.swing.JLabel BackgroundKeywordAnalysis;
    private javax.swing.JLabel BackgroundResumeBuilder;
    private javax.swing.JButton JobMatch;
    private javax.swing.JButton KeywordAnalysis;
    private javax.swing.JLabel Resume;
    private javax.swing.JButton ResumeBuilder;
    // End of variables declaration//GEN-END:variables
}
