
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sajid
 */
public class ResumeBuilder extends javax.swing.JFrame {

    
    
    /**
     * Creates new form ResumeBuildedr
     */
    public ResumeBuilder() {
        initComponents();
        
        BackgroundProceed1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProceedFirst = new javax.swing.JButton();
        Github = new javax.swing.JTextField();
        Linkedin = new javax.swing.JTextField();
        PhoneNum = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        BackgroundProceed1 = new javax.swing.JLabel();
        BackgroundMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProceedFirst.setText("jButton1");
        ProceedFirst.setBorderPainted(false);
        ProceedFirst.setContentAreaFilled(false);
        ProceedFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProceedFirstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProceedFirstMouseExited(evt);
            }
        });
        ProceedFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedFirstActionPerformed(evt);
            }
        });
        getContentPane().add(ProceedFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 670, 150, 160));

        Github.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Github.setBorder(null);
        getContentPane().add(Github, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 713, 650, 40));

        Linkedin.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Linkedin.setBorder(null);
        getContentPane().add(Linkedin, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, 650, 40));

        PhoneNum.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        PhoneNum.setBorder(null);
        PhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 650, 40));

        Email.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Email.setBorder(null);
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 650, 40));

        Name.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Name.setBorder(null);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 402, 650, 40));

        BackgroundProceed1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resume_proceed1.png"))); // NOI18N
        getContentPane().add(BackgroundProceed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgroundMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resume_main.png"))); // NOI18N
        getContentPane().add(BackgroundMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void ProceedFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedFirstActionPerformed
        try {
            StoreInfoFirst();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ResumeBuilder.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(ResumeBuilder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProceedFirstActionPerformed

    private void ProceedFirstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProceedFirstMouseEntered
        BackgroundProceed1.setVisible(true);
    }//GEN-LAST:event_ProceedFirstMouseEntered

    private void ProceedFirstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProceedFirstMouseExited
       BackgroundProceed1.setVisible(false);
    }//GEN-LAST:event_ProceedFirstMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumeBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumeBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumeBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumeBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumeBuilder().setVisible(true);
            }
        });
    }
    
    void StoreInfoFirst() throws FileNotFoundException, UnsupportedEncodingException {
        PrintWriter writer = new PrintWriter("data/info.txt", "UTF-8");
        writer.println(Name.getText());
        writer.println(Email.getText());
        writer.println(PhoneNum.getText());
        writer.println(Linkedin.getText());
        writer.println(Github.getText());
        writer.close();
    }
    
    void StoreInfoSecond() throws FileNotFoundException, UnsupportedEncodingException {
        PrintWriter writer = new PrintWriter("data/info.txt", "UTF-8");
        writer.println(Name.getText());
        writer.println(Email.getText());
        writer.println(PhoneNum.getText());
        writer.println(Linkedin.getText());
        writer.println(Github.getText());
        writer.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundMain;
    private javax.swing.JLabel BackgroundProceed1;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Github;
    private javax.swing.JTextField Linkedin;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PhoneNum;
    private javax.swing.JButton ProceedFirst;
    // End of variables declaration//GEN-END:variables
}
